// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiayTheThao.Data;

#nullable disable

namespace WebBanGiayTheThao.Migrations
{
    [DbContext(typeof(QuanLyWebBanGiayContext))]
    [Migration("20260117043805_ThemTrangThaiChoLienHe")]
    partial class ThemTrangThaiChoLienHe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanGiayTheThao.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int?>("Sao")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BinhLuan__3214EC07CEA3D11E");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("UserId");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Ctanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LinkAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CTAnh__3214EC07E170B2DF");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CTAnh");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.CtgioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CTGioHan__3214EC07B72D9525");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("SizeId");

                    b.HasIndex("UserId");

                    b.ToTable("CTGioHang");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.CthoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HoaDonId", "SanPhamId", "SizeId")
                        .HasName("PK__CTHoaDon__4284F3BD8B941929");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("SizeId");

                    b.ToTable("CTHoaDon");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Ctsize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<double?>("Size")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("SoLuongTon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__CTSize__3214EC07E64E7E18");

                    b.HasIndex("SanPhamId");

                    b.ToTable("CTSize");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiNhan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNguoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaVoucher")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PhuongThucThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("Sdtnhan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDTNhan");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HoaDon__3214EC079B9FB4B5");

                    b.HasIndex("UserId");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.LienHe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__LoaiSanP__3214EC07B04E48E2");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DonGia")
                        .IsRequired()
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("LoaiSanPhamId")
                        .HasColumnType("int");

                    b.Property<string>("MaKieuDang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThuongHieuId")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__SanPham__3214EC07B8D26B72");

                    b.HasIndex("LoaiSanPhamId");

                    b.HasIndex("ThuongHieuId");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.SlideShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__SlideSho__3214EC07E9487E13");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("SlideShow");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.ThuongHieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ThuongHi__3214EC076F1C9602");

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC07B77DCB15");

                    b.HasIndex(new[] { "Username" }, "UQ__User__536C85E4699D81D4")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.UserVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("DonToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("NgayNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserVouc__3214EC0746346C64");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVoucher");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaTriDonToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaTriGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Voucher__3214EC07454989EB");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.WebSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hotline")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__WebSetti__3214EC079FCF25EB");

                    b.ToTable("WebSetting");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.BinhLuan", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.SanPham", "SanPham")
                        .WithMany("BinhLuans")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__BinhLuan__SanPha__60A75C0F");

                    b.HasOne("WebBanGiayTheThao.Models.User", "User")
                        .WithMany("BinhLuans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__BinhLuan__UserId__5FB337D6");

                    b.Navigation("SanPham");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Ctanh", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.SanPham", "SanPham")
                        .WithMany("Ctanhs")
                        .HasForeignKey("SanPhamId")
                        .HasConstraintName("FK__CTAnh__SanPhamId__4CA06362");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.CtgioHang", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.SanPham", "SanPham")
                        .WithMany("CtgioHangs")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__CTGioHang__SanPh__5AEE82B9");

                    b.HasOne("WebBanGiayTheThao.Models.Ctsize", "Size")
                        .WithMany("CtgioHangs")
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("FK__CTGioHang__SizeI__5BE2A6F2");

                    b.HasOne("WebBanGiayTheThao.Models.User", "User")
                        .WithMany("CtgioHangs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CTGioHang__UserI__59FA5E80");

                    b.Navigation("SanPham");

                    b.Navigation("Size");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.CthoaDon", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.HoaDon", "HoaDon")
                        .WithMany("CthoaDons")
                        .HasForeignKey("HoaDonId")
                        .IsRequired()
                        .HasConstraintName("FK__CTHoaDon__HoaDon__6754599E");

                    b.HasOne("WebBanGiayTheThao.Models.SanPham", "SanPham")
                        .WithMany("CthoaDons")
                        .HasForeignKey("SanPhamId")
                        .IsRequired()
                        .HasConstraintName("FK__CTHoaDon__SanPha__68487DD7");

                    b.HasOne("WebBanGiayTheThao.Models.Ctsize", "Size")
                        .WithMany("CthoaDons")
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("FK__CTHoaDon__SizeId__693CA210");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Ctsize", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.SanPham", "SanPham")
                        .WithMany("Ctsizes")
                        .HasForeignKey("SanPhamId")
                        .HasConstraintName("FK__CTSize__SanPhamI__5070F446");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.HoaDon", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.User", "User")
                        .WithMany("HoaDons")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__UserId__6477ECF3");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.SanPham", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamId")
                        .HasConstraintName("FK__SanPham__LoaiSan__49C3F6B7");

                    b.HasOne("WebBanGiayTheThao.Models.ThuongHieu", "ThuongHieu")
                        .WithMany("SanPhams")
                        .HasForeignKey("ThuongHieuId")
                        .HasConstraintName("FK__SanPham__ThuongH__48CFD27E");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.UserVoucher", b =>
                {
                    b.HasOne("WebBanGiayTheThao.Models.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserVouch__UserI__5535A963");

                    b.HasOne("WebBanGiayTheThao.Models.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("FK__UserVouch__Vouch__5629CD9C");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Ctsize", b =>
                {
                    b.Navigation("CtgioHangs");

                    b.Navigation("CthoaDons");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.HoaDon", b =>
                {
                    b.Navigation("CthoaDons");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.SanPham", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("Ctanhs");

                    b.Navigation("CtgioHangs");

                    b.Navigation("CthoaDons");

                    b.Navigation("Ctsizes");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.User", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("CtgioHangs");

                    b.Navigation("HoaDons");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("WebBanGiayTheThao.Models.Voucher", b =>
                {
                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
